drake_lyrics = ["We don't like to do too much explaining \nStory stayed the same, I never changed it",
"As I’m back in the city they throw a parade \nI might get a key to the city and give it to Wayne \nOr give it to one of the young boys to carry the wave",
"Me and my friends we got money to spend",
"I guess you lose some and win some \nLong as the outcome is income",
"I'm honest, I make mistakes, I'd be the second to admit it \nThink that's why I need her in my life, to check me when I'm trippin",
"Pray the real live forever, man \nPray the fakes get exposed",
"Just hold on, we're going home",
"Fuck goin' online that ain't part of my day",
"I think I'm addicted to naked pictures",
"I’m hearing all of the jokes, I know that they tryna push me \nI know that showing emotion don’t ever mean I’m a pussy",
"My high school reunion might be worth an appearance \nMake everybody have to go through security clearance",
"I could load every gun with bullets that fire backwards \nYou probably wouldn't lose a single rapper",
"Tuck my napkin in my shirt, cause I'm just mobbin' like that",
"I'm way up \nI feel blessed",
"I swear this life is like the sweetest thing I've ever known",
"I'm living life right now man and this what imma do til it's over",
"I cannot see heaven being much better than this",
"I live for the nights that I can't remember with the people that I won't forget",
"My team good, we don't really need a mascot",
"I still ride with my day one",
"You the best I ever had",
"I got the drink in me goin' back to back",
"World Series attitude, champagne bottle life",
"Somewhere between I'm sober and I'm lifted",
"Drinking every night because we drink to my accomplishments",
"Imma sip it 'til i feel it, Imma smoke it 'til it's done",
"Let's celebrate with a toast and get lost in tonight",
"Twenty-four-hour champagne diet",
"Live for today, plan for tomorrow, party tonight",
"I'm here for a good time not a long time",
"On my worst behavior",
"My excuse is that I'm young",
"You only live once",
"Ask you to please excuse my table manners \nI was making room for the table dancers",
"Where you movin?\nI said onto better things",
"Worrying about your followers\nyou need to get your dollars up",
"I'm up right now and you suck right now",
"I'm just saying you could do better",
"Imma worry 'bout me, give a fuck about you",
"If you think I'mma quit before I die dream on",
"Pray the real live forever man\nPray the fakes get exposed",
"Think before you come for the great one",
"If I die all i know is I'm a mothafuckin' legend",
"Know yourself, know your worth",
"Every time you see me I look like I hit the lotto twice",
"Call me the referee because I be so official",
"Last name ever, first name greatest",
"Started from the bottom now we're here",
"Fresher than a pillow with a mint on it",
"I'm on a roll like Cottonelle",
"They ain't make me what I am, they just found me like this",
"Sweatpants, hair tied, chillin' with no makeup on",
"Started not to give a fuck and stopped fearing the consequence"]

